[package]
name = "rbxmidi"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
midi-control = "0.2.2"
midir = "0.10.0"
ron = "0.8"
serde = { version = "1", features = ["derive"] }